django/just_a_code/catalog/urls.py
from django import forms
from django.conf.urls import url, patterns


from forms import FilesForm, DealTypeForm, LocationForm
from views import AddObjectWizard

named_contact_forms = (
    ('deal_type', DealTypeForm),
    ('location', LocationForm),
    ('object', forms.Form),
    ('files', FilesForm),
)

def it_not_demand(wizard):
    cleaned_data = wizard.get_cleaned_data_for_step('deal_type') or {}
    deal_type = cleaned_data.get('deal_type')
    if deal_type:
        return deal_type.slug != 'demand'

    return True


add_object_wizard = AddObjectWizard.as_view(named_contact_forms,
    url_name='add_object_step',
    done_step_name='finished',
    condition_dict={
        'deal_type': True,
        'location': it_not_demand,
        'object': it_not_demand,
        'files': it_not_demand
    }
)

urlpatterns = patterns('catalog.views',
    url(r'^add/(?P<step>.+)/$', add_object_wizard, name='add_object_step'),
    url(r'^add/$', add_object_wizard, name='add_object'),
    url(r'^get_sub_cats/(?P<category_id>\d+)/$', 'get_sub_cats'),

    url(r'^get_deal_type_info/(?P<deal_type_id>\d+)/$', 'get_deal_type_info'),
    url(r'^get_category_info/(?P<category_id>\d+)/$', 'get_category_info'),


    url(r'^my_items/$', 'my_products', name='my_products'),
    url(r'^(?P<product_id>\d+)/delete_item/$', 'delete_product', name='delete_product'),
    url(r'^(?P<product_id>\d+)/edit_item/$', 'edit_product', name='edit_product'),
    url(r'^(?P<product_id>\d+)/edit_demand/$', 'edit_demand', name='edit_demand'),
    url(r'^(?P<product_id>\d+)/edit_item/photos/$', 'edit_product_photos', name='edit_product_photos'),
    url(r'^(?P<product_id>\d+)/edit_item/map/$', 'edit_product_map', name='edit_product_map'),
    url(r'^(?P<product_id>\d+)/success/$', 'successfully_added', name='successfully_added'),
    url(r'^$', 'view_region', name='view_region'),
    url(r'^map/$', 'view_region_map', name='view_region_map'),
)

django/just_a_code/catalog/forms.py
# -*- coding: utf-8
from crispy_forms.bootstrap import FormActions, TabHolder, Tab, AppendedText, PrependedAppendedText

from django import forms

from file_resubmit import AdminResubmitImageWidget
from catalog.models import Category, METRO_DIST_TYPE, DEAL_PRICE_TYPE, DEAL_PRICE_PERIOD, DealType, FieldSet, Price, Location, ProductImage, Product


from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, HTML, Row, Field, Fieldset, Div
from regions.models import GeoLocation


class FindByIDForm(forms.Form):
    product_id = forms.IntegerField()

    def clean_product_id(self):
        product_id =  self.cleaned_data['product_id']

        try:
            Product.approved_objects.get(pk=product_id)
        except Product.DoesNotExist:
            raise forms.ValidationError(u"Объект не найден")

        return product_id


class DealTypeForm(forms.Form):
    deal_type = forms.ModelChoiceField(queryset=DealType.objects.all(), label=u'Тип сделки')
    region = forms.ModelChoiceField(queryset=GeoLocation.objects.all(), label='Регион', empty_label=None)
    category = forms.ModelChoiceField(queryset=Category.objects.filter(parent=None), label=u'Вид недвижимости')
    title = forms.CharField(label=u'Заголовок объявления')
    description = forms.CharField(widget=forms.widgets.Textarea, label=u'Текст объявления')
    price = forms.DecimalField(max_digits=12, decimal_places=2, label=u'Стоимость')
    price_type = forms.ChoiceField(choices=DEAL_PRICE_TYPE, required=False)
    price_period = forms.ChoiceField(choices=DEAL_PRICE_PERIOD, required=False)
    commission = forms.DecimalField(max_digits=12, decimal_places=2, required=False)
    pledge = forms.DecimalField(max_digits=12, decimal_places=2, required=False)

    helper = FormHelper()
    helper.form_tag = False
    helper.form_class = 'form-horizontal'
    helper.layout = Layout(
        Fieldset(
            u'Основная информация',
            Field('deal_type', css_class='input-xlarge'),

            Field('category', rows="3", css_class='input-xlarge'),
            Field('title', rows="3", css_class='input-xxlarge'),
            Field('description', rows="9", css_class='input-xxlarge'),
            Field('region', css_class='input-xlarge'),
            Div(
                # HTML(
                #     u'<div class="control-group"><label for="inlineCheckboxes" class="control-label">Стоимость<span class="asteriskField">*</span></label><div class="controls">')
                # ,
                AppendedText('price', text='руб', css_class='input-small', ),
                Field('price_period', css_class='input-small', template='catalog/elements/inline_field.html'),
                Field('price_type', css_class='input-small', template='catalog/elements/inline_field.html'),

            ),
            Div(
                HTML(
                    u'<div class="control-group"><label for="inlineCheckboxes" class="control-label">Комиссия агента<span class="asteriskField"></span></label><div class="controls">')
                ,
                Field('commission', css_class='input-small', template='catalog/elements/inline_field.html'),
                HTML(u'</div></div>'),
            ),
            Div(
                HTML(
                    u'<div class="control-group"><label for="inlineCheckboxes" class="control-label">Залог собственника</label><div class="controls">')
                ,
                Field('pledge', css_class='input-small', template='catalog/elements/inline_field.html'),
                HTML(u'</div></div>'),
            ),
        )

    )


    def clean(self):
        cleaned_data = super(DealTypeForm, self).clean()

        if 'deal_type' in cleaned_data and not cleaned_data['deal_type'].show_price_field:
            if 'price' in self._errors:
                del self._errors["price"]

        return cleaned_data


class LocationForm(forms.ModelForm):
    region = forms.ModelChoiceField(queryset=GeoLocation.objects.all(), label='Регион', empty_label=None)
    city = forms.CharField(max_length=255, label=u'Населенный пункт')

    metro = forms.CharField(max_length=255, required=False, label=u'Метро')
    metro_dist = forms.CharField(max_length=255, required=False, label=u'До метро')
    metro_dist_type = forms.ChoiceField(choices=METRO_DIST_TYPE, required=False, label=u'Как')

    metro_alt = forms.CharField(max_length=255, required=False, label=u'Метро 2')
    metro_alt_dist = forms.CharField(max_length=255, required=False, label=u'До метро 2')
    metro_alt_dist_type = forms.ChoiceField(choices=METRO_DIST_TYPE, required=False, label=u'Как')

    address = forms.CharField(max_length=255, label=u'Адрес (улица, дом)', required=False)

    lat = forms.CharField(widget=forms.HiddenInput(), required=False)
    lng = forms.CharField(widget=forms.HiddenInput(), required=False)
    zoom_level = forms.CharField(widget=forms.HiddenInput(), required=False)
    metro_available = forms.BooleanField(widget=forms.HiddenInput(), required=False, initial=False)

    helper = FormHelper()
    helper.form_tag = False
    helper.form_class = 'form-horizontal'
    helper.layout = Layout(
        Fieldset(
            u'Месторасположение',
            Field('region', css_class='input-xlarge'),
            Field('city', css_class='input'),
            Field('address', css_class='input'),
            'lat', 'lng', 'zoom_level', 'metro_available',
            Row(
                HTML(
                    u'<div class="control-group metro"><label for="inlineCheckboxes" class="control-label">Метро</label><div class="controls">')
                ,
                Field('metro', css_class='input-small', template='catalog/elements/inline_field.html'),
                Field('metro_dist', css_class='input-medium', template='catalog/elements/inline_field.html'),
                Field('metro_dist_type', css_class='input-medium', template='catalog/elements/inline_field.html'),
                HTML(u'<br/><a href=# class="add_metro">Добавить еще одно метро</a>'),
                HTML(u'</div></div>'),
            ),
            Row(
                HTML(
                    u'<div class="control-group metro-alt"><label for="inlineCheckboxes" class="control-label">Метро 2</label><div class="controls">')
                ,
                Field('metro_alt', css_class='input-small', template='catalog/elements/inline_field.html'),
                Field('metro_alt_dist', css_class='input-medium', template='catalog/elements/inline_field.html'),
                Field('metro_alt_dist_type', css_class='input-medium', template='catalog/elements/inline_field.html'),
                HTML(u'</div></div>'),
            ),
            HTML(u'<div class="control-group"><label class="control-label">На карте:</label><div class="controls">'),
            HTML(
                u'<div class="additional_button"><a class="btn" id="geolocation" href="#">Отметить на карте</a></div></br>')
            ,
            HTML(u'<div id="map" style="width:800px; height:400px"></div>'),
            HTML(u'<p class="muted">Масштаб будет учитываться при показе карты на странице объекта</p>'),
            HTML(u'</div></div>'),
        )

    )

    def clean(self):
        cleaned_data = super(LocationForm, self).clean()
        print cleaned_data

        if cleaned_data['metro_available'] == True and cleaned_data['metro'] == '':
            msg = u"Укажите метро"
            self._errors["metro"] = self.error_class([msg])
            del cleaned_data["metro"]

        if cleaned_data['metro_available'] == True and cleaned_data['metro_dist'] == '':
            msg = u"Укажите расстояние от метро"
            self._errors["metro_dist"] = self.error_class([msg])
            del cleaned_data["metro_dist"]

        return cleaned_data


    def __init__(self, *args, **kwargs):
        super(LocationForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Location
        exclude = ('product',)


class ImageForm(forms.ModelForm):
    image = forms.ImageField(required=False, label=u'Изображение') # widget=AdminResubmitImageWidget)

    helper = FormHelper()
    helper.form_tag = False
    helper.form_class = 'form-horizontal'
    helper.layout = Layout(
        Fieldset(
            Field('files-TOTAL_FORMS'),
            Field('files-INITIAL_FORMS'),
            Field('files-MAX_NUM_FORMS'),
            Field('image', css_class='input-xlarge'),
        )
    )

    class Meta:
        model = ProductImage
        exclude = ('product',)


from django.forms.formsets import formset_factory

ImageFormSet = formset_factory(ImageForm)



class FilesForm(forms.Form):
    image = forms.ImageField(widget=AdminResubmitImageWidget)

    helper = FormHelper()
    helper.form_tag = False

    helper.layout = Layout(
        Fieldset(
            u'Files',
            Field('image', css_class='input-xlarge'),
        )
    )



class DynamicForm(forms.Form):
    helper = FormHelper()
    helper.form_tag = False
    helper.form_class = 'form-horizontal'


    def __init__(self, *args, **kwargs):

        self.category = kwargs.pop('category', None)
        self.deal_type = kwargs.pop('deal_type', None)

        super(DynamicForm, self).__init__(*args, **kwargs)

        fsets = FieldSet.objects.filter(
            field__id__in=[x.field.id for x in self.category.fields.filter(deal_types=self.deal_type)]).distinct()

        form_field_sets = []

        for fs in fsets:

            form_field_set = Fieldset(fs.name)

            for f in self.category.fields.filter(field__field_set=fs, deal_types=self.deal_type).order_by(
                    'weight').distinct():

                field_name = 'field_%s' % f.field.id
                field_name_additional = 'field_%s_additional' % f.field.id

                if f.field.type == u'BooleanField':
                    self.fields[field_name] = forms.BooleanField(label=f.field.name, required=False)

django/just_a_code/catalog/templates/catalog/add_object_wizard/location_script.html
<script src="http://api-maps.yandex.ru/2.0/?load=package.full&lang=ru-RU" type="text/javascript"></script>

<script type="text/javascript" charset="utf-8">

    $(function(){

        // Метро

        {% if not request.location.metro %}
            $(".metro-alt, .metro").parent().hide();
        {% endif %}

        // Можно добавить еще одно метро
        $("a.add_metro").on('click',function(){
            $(".metro-alt").parent().toggle();
            return false;
        });

        // Рисуем карту
        ymaps.ready(init);

        {% with request.location.lat|stringformat:"f" as lat %}
            {% with request.location.lng|stringformat:"f" as lng %}



                console.log($("#id_{{prefix}}zoom_level").val())
                if ($("#id_{{prefix}}lat").val() == '' || $("#id_{{prefix}}lng").val()=='') {
                    var lat = {{ lat }};
                    var lng = {{ lng }};
                } else
                {
                    var lat = $("#id_{{prefix}}lat").val();
                    var lng = $("#id_{{prefix}}lng").val();
                }
                console.log(lat, lng)
                var zoom_level = $("#id_{{prefix}}zoom_level").val();

                var myMap;
                var myPlacemark;

                function updateCoordinates() {
                    var lat = myPlacemark.geometry.getCoordinates()[0];
                    var lng = myPlacemark.geometry.getCoordinates()[1];
                    $("#id_{{prefix}}lat").val(lat);
                    $("#id_{{prefix}}lng").val(lng);
                }

                function init () {
                    myMap = new ymaps.Map("map", {
                        center: [lat, lng],
                        zoom: zoom_level
                    });

                    myMap.controls
                        // Список типов карты
                            .add('typeSelector')
                            .add('smallZoomControl', { right: 5, top: 75 })

                    // Первый способ задания метки
                    myPlacemark = new ymaps.Placemark([lat, lng],{},{draggable: true})


                    // Добавляем метки на карту
                    myMap.geoObjects.add(myPlacemark)


                    $('#geolocation').on('click',function(){

                        var selected_region_id = $("#id_{{prefix}}region option:selected").val();
                        $.getJSON("/regions/get_location_info/"+selected_region_id+"/",{}, function(response){

                            var adr = response['region_name'] + ',' + $("#id_{{prefix}}city").val() + ',' + $("#id_{{prefix}}address").val();
                            console.log(adr);
                            ymaps.geocode(adr, { results: 1 }).then(function (res) {
                                // Выбираем первый результат геокодирования
                                var firstGeoObject = res.geoObjects.get(0);
                                if (firstGeoObject) {
                                    myPlacemark.geometry.setCoordinates(firstGeoObject.geometry.getCoordinates())
                                    myMap.setCenter(myPlacemark.geometry.getCoordinates())
                                    updateCoordinates();
                                }
                            });
                        });

                        return false;
                    });

                    myPlacemark.events.add('drag', function () {
                        updateCoordinates();
                    });

                    myMap.events.add(['move','boundschange'], function(e) {
                        $("#id_{{prefix}}zoom_level").val(e.getMap().getZoom());
                    });



                    $("#id_{{prefix}}region").on('change', function(){
                        $.getJSON("/regions/get_location_info/"+$(this).val()+"/",{}, function(response){
                            var lat = response['lat'];
                            var lng = response['lng'];
                            var zoom = response['zoom'];
                            var metro = response['metro'];

                            myPlacemark.geometry.setCoordinates([lat,lng])
                            myMap.setCenter(myPlacemark.geometry.getCoordinates())
                            myMap.setZoom(zoom);

                            if (metro) {
                                $(".metro").parent().show();
                                $("#id_{{prefix}}metro_available").val(1);
                            } else {
                                $(".metro").parent().hide();
                                $(".metro-alt").parent().hide();
                                $("#id_{{prefix}}metro_available").val(0);
                            }

                        });
                    });

                {% if edit_mode %}

                {% else %}
                    $("#id_{{prefix}}region").change()
                {% endif %}




                }

            {% endwith %}
        {% endwith %}

    })
</script>

django/just_a_code/catalog/templates/catalog/add_object_wizard/step_deal_type.html
{% extends "catalog/add_object_wizard/wizard_form.html" %}

{% block extra_meta %}
    {{ block.super }}
    <script type="text/javascript" charset="utf-8">

        var SELL = 1;
        var RENT = 2;

        var DIFFERENT_PRICE_TYPES_FOR = [4];

        $(function(){

            // Изменился тип сделки
            $("select#id_deal_type-deal_type").change(function(){

                var commission_rows = $('#id_deal_type-commission').parent().parent().parent().parent();
                var pledge_rows = $('#id_deal_type-pledge').parent().parent().parent().parent();
                var period_rows = $('label[for=id_deal_type-price_period]')
                var price_rows = $('#id_deal_type-price').parent().parent().parent().parent();
                var region_rows = $('#id_deal_type-region').parent().parent();

                var val = this.value;

                if (val) {
                    $.getJSON('/catalog/get_deal_type_info/'+val+'/', function(data){
                        console.log(data);
                        var html = '';
                        var len = data.categories.length;
                        for (var i = 0; i< len; i++) {
                            html += '<option value="' + data.categories[i][0] + '">' + data.categories[i][1] + '</option>';
                        }
                        $('#id_deal_type-category').html(html);

                        commission_rows.toggle(data.info['show_commission_field'])
                        pledge_rows.toggle(data.info['show_pledge_field'])
                        period_rows.toggle(data.info['show_period_field'])
                        price_rows.toggle(data.info['show_price_field'])
                        region_rows.toggle(!data.info['show_price_field'])

                        if (data.info['slug'] == 'demand') {
                            $('div.control-group div.controls input.btn-primary').attr('value', 'Сохранить')
                        } else {
                            $('div.control-group div.controls input.btn-primary').attr('value', 'Далее')
                        }


                    });
                } else {
                    $('#id_deal_type-category').find('option').remove().end().append('<option value="">---------</option>').val('');
                    commission_rows.hide();
                    pledge_rows.hide();
                    period_rows.hide();
                    region_rows.hide();
                }
            }).change();

            // Изменился тип недвижимости
            $("select#id_deal_type-category").on('change',function(){

                var selector = $('label[for=id_deal_type-price_type]');

                selector.hide()

                if ($(this).val()) {
                    $.getJSON("/catalog/get_category_info/"+$(this).val()+"/",{}, function(response){

                        var data = response;
                        if (data['info']['show_additional_price_options']) {
                            selector.show()
                        } else {
                            selector.hide()
                        }
                    });
                }
            }).change();


        })
    </script>
{% endblock %}

{% block wizard_step %}{% endblock %}

django/just_a_code/catalog/templates/catalog/add_object_wizard/step_files.html
{% extends "catalog/add_object_wizard/wizard_form.html" %}

{% block extra_meta %}
    {{ block.super }}
    <script type="text/javascript">
        $(document).ready(function(){
            $('.add-file').click(function(ev){
                ev.preventDefault();
                var count = $('.files').children().length;
                var tmplMarkup = $('#file-template').html();
                var compiledTmpl = _.template(tmplMarkup, { id : count });
                $('div.files').append(compiledTmpl);
                // update form count
                $('#id_files-TOTAL_FORMS').attr('value', count+1);
            });
        })
    </script>

    <script type="text/html" id="file-template">
        <div id="file-<%= id %>">
            <label for="id_files-<%= id %>-image">Изображение:</label>
            <input id="id_files-<%= id %>-image" type="file" name="files-<%= id %>-image">
        </div>
    </script>

{% endblock %}


{% block form_data %}
        {{ wizard.form.management_form }}

        <div class="files">
            {% for form in wizard.form.forms %}
                <div id="file-{{ forloop.counter0 }}">
                    {{ form }}
                </div>
            {% endfor %}
        </div>

        <div class="form-actions">
            <a href="#" class="btn btn-info add-file">Добавить файл</a>
        </div>
{% endblock %}

django/just_a_code/catalog/templates/catalog/add_object_wizard/step_location.html
{% extends "catalog/add_object_wizard/wizard_form.html" %}



{% block extra_meta %}
    {{ block.super }}
    {% include 'catalog/add_object_wizard/location_script.html' with prefix='location-' %}
{% endblock %}

django/just_a_code/catalog/templates/catalog/add_object_wizard/step_object.html
{% extends "catalog/add_object_wizard/wizard_form.html" %}

{% block extra_meta %}
    {{ block.super }}
    <script type="text/javascript" charset="utf-8">

    </script>
{% endblock %}

django/just_a_code/catalog/templates/catalog/add_object_wizard/wizard_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block head %}
    {{ wizard.form.media }}
{% endblock %}


{% block content %}
    <p>Шаг {{ wizard.steps.step1 }} из {{ wizard.steps.count }}</p>
    <form action="" method="post" class="form-horizontal" enctype='multipart/form-data'>{% csrf_token %}
        {{ wizard.management_form }}

        {% block form_data %}
            {% if wizard.form.forms %}
                {{ wizard.form.management_form }}

                {% for form in wizard.form.forms %}
                    {% crispy form %}
                {% endfor %}

            {% else %}
                {% crispy wizard.form wizard.form.helper %}
            {% endif %}
        {% endblock %}

        <div class="control-group">
            <div class="controls">

                {% if wizard.steps.next %}
                    <input type="submit" value="Далее" class="btn btn-primary"/>
                {% else %}
                    <input type="submit" value="Завершить добавление публикации" class="btn btn-primary"/>
                {% endif %}
                {% if wizard.steps.prev %}
                    &nbsp; или &nbsp;
                    <button class="btn" name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">Назад</button>
                {% endif %}

            </div>
        </div>

    </form>
{% endblock %}