django/just_a_code/catalog/urls.py
from django import forms
from django.conf.urls import url, patterns


from forms import FilesForm, DealTypeForm, LocationForm
from views import AddObjectWizard

named_contact_forms = (
    ('deal_type', DealTypeForm),
    ('location', LocationForm),
    ('object', forms.Form),
    ('files', FilesForm),
)

def it_not_demand(wizard):
    cleaned_data = wizard.get_cleaned_data_for_step('deal_type') or {}
    deal_type = cleaned_data.get('deal_type')
    if deal_type:
        return deal_type.slug != 'demand'

    return True


add_object_wizard = AddObjectWizard.as_view(named_contact_forms,
    url_name='add_object_step',
    done_step_name='finished',
    condition_dict={
        'deal_type': True,
        'location': it_not_demand,
        'object': it_not_demand,
        'files': it_not_demand
    }
)

urlpatterns = patterns('catalog.views',
    url(r'^add/(?P<step>.+)/$', add_object_wizard, name='add_object_step'),
    url(r'^add/$', add_object_wizard, name='add_object'),
    url(r'^get_sub_cats/(?P<category_id>\d+)/$', 'get_sub_cats'),

    url(r'^get_deal_type_info/(?P<deal_type_id>\d+)/$', 'get_deal_type_info'),
    url(r'^get_category_info/(?P<category_id>\d+)/$', 'get_category_info'),


    url(r'^my_items/$', 'my_products', name='my_products'),
    url(r'^(?P<product_id>\d+)/delete_item/$', 'delete_product', name='delete_product'),
    url(r'^(?P<product_id>\d+)/edit_item/$', 'edit_product', name='edit_product'),
    url(r'^(?P<product_id>\d+)/edit_demand/$', 'edit_demand', name='edit_demand'),
    url(r'^(?P<product_id>\d+)/edit_item/photos/$', 'edit_product_photos', name='edit_product_photos'),
    url(r'^(?P<product_id>\d+)/edit_item/map/$', 'edit_product_map', name='edit_product_map'),
    url(r'^(?P<product_id>\d+)/success/$', 'successfully_added', name='successfully_added'),
    url(r'^$', 'view_region', name='view_region'),
    url(r'^map/$', 'view_region_map', name='view_region_map'),
)

django/just_a_code/catalog/models.py
# -*- coding: utf-8
import os
import datetime
from django.contrib.auth.models import User

from django.db import models
from django.contrib.sites.models import Site
from django.db.models import permalink, Q
from django.db.models.signals import pre_save
from easy_thumbnails.fields import ThumbnailerImageField
from mptt.models import MPTTModel
from pytils.translit import slugify
from dict.models import Dict
from django_hstore import hstore


from model_utils.models import TimeStampedModel
from regions.models import GeoLocation

WALKING = 1
TRANSPORT = 2

METRO_DIST_TYPE = (
    (WALKING, u'Пешком'),
    (TRANSPORT, u'На транспорте'),
)

DEAL_PRICE_TYPE = [(1,'Объект'), (2, 'Сотка'),(2, 'Кв. метр')]
DEAL_PRICE_PERIOD = [(1,'Месяц'), (2, 'Год')]


FIELD_TYPE = (
    ('BooleanField', u'Да/Нет'),
    ('CharField', u'Строка'),
    ('TextField', u'Текст'),
    ('ChoiceField', u'Выбор из списка'),
)


class DealType(models.Model):
    """
    Вид сделки
    """
    name = models.CharField(u'Название', max_length=255)
    show_commission_field = models.BooleanField(u'Отображать комиссию агента', default=False)
    show_pledge_field = models.BooleanField(u'Отображать залог собственника', default=False)
    show_period_field = models.BooleanField(u'Отображать поля выбора периода', default=False)
    show_price_field = models.BooleanField(u'Отображать поле ввода стоимости', default=True)
    slug = models.SlugField(unique=True, help_text=u'Не редактировать это поле без согласования с программистом')

    def __unicode__(self):
        return u'%s' % self.name

    class Meta:
        verbose_name = u'Тип сделки'
        verbose_name_plural = u'Типы сделок'


class FieldSet(models.Model):
    """
    Набор полей
    """
    name = models.CharField(max_length=255)
    comment = models.CharField(max_length=255, blank=True, null=True)
    weight = models.IntegerField(u'Сортировка', blank=True, null=True, default=0, help_text=u'Чем меньше число тем выше строка в списке')

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'Набор полей'
        verbose_name_plural = u'Наборы полей'
        ordering = ['weight',]


class Field(models.Model):
    """
    Поле с названием и типом (например: Браузер, тип=Одиночный выбор)
    """
    name = models.CharField(u'Название', max_length=255)
    type = models.CharField(u'Тип', choices=FIELD_TYPE, default='CharField', max_length=255)
    additional_info = models.BooleanField(u'Отобржать строчку для описания', default=False)
    field_set = models.ForeignKey(FieldSet, verbose_name=u'Набор полей')
    css_class = models.CharField(u'CSS класс', max_length=255, blank=True, null=True, default='input-xxlarge')
    code = models.CharField(max_length=255, unique=True, help_text=u'Не редактировать это поле без согласования с программистом')

    def __unicode__(self):
        return u'%s (%s) | %s' % (self.name, self.get_type_display(), self.field_set.name)

    class Meta:
        verbose_name = u'Поле'
        verbose_name_plural = u'Поля'
        ordering = ['field_set']



class CatetegoryTypeFieldValue(models.Model):
    """
    Вышеописанное поле привязанное к категории и его значение
    """
    category = models.ForeignKey('Category', related_name='fields', verbose_name=u'Категория')
    field = models.ForeignKey(Field)
    required = models.BooleanField(u'Обязательно для заполнения', blank=True, default=False)

    value_bool = models.BooleanField(blank=True, default=False)
    value_text = models.CharField(max_length=255, blank=True, null=True)
    value_choice = models.ManyToManyField(Dict, blank=True, null=True, related_name='choices')
    comment = models.TextField(blank=True, null=True)
    deal_types = models.ManyToManyField(DealType, verbose_name=u'Отображать при следующих сделках')

    weight = models.IntegerField(u'Сортировка', blank=True, null=True, default=0, help_text=u'Чем меньше число тем выше строка в списке')

    def __unicode__(self):
        return u"%s - %s" % (self.category.name, self.field.name)

    class Meta:
        verbose_name = u'Значение поля в категории'
        verbose_name_plural = u'Значения полей в категориях'


def category_upload_to(instance, filename):
    return os.path.join('categories', 'small_images', str(instance.id), filename)


class Category(MPTTModel):
    """
    Категория объекта
    """
    parent = models.ForeignKey('self', blank=True, null=True, related_name='childrens')
    name = models.CharField(max_length=255)
    show_additional_price_options = models.BooleanField(u'Отображать доп. параметры стоимости', default=False)
    deal_types = models.ManyToManyField(DealType, verbose_name=u'Отображать при следующих сделках')
    slug = models.SlugField(unique=True, help_text=u'Не редактировать это поле без согласования с программистом')
    small_image = ThumbnailerImageField(u'Изображение маленькое', blank=True, null=True, upload_to=category_upload_to, help_text=u'Для главной')
    show_on_main = models.BooleanField(u'Отображать на главной', default=False, help_text=u'Отображать на главной странице в виде картинки')

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'Тип объекта'
        verbose_name_plural = u'Типы объектов'

    def get_fields(self):
        fields = []

        ancestors_cats = self.get_ancestors(include_self=True)
        for c in ancestors_cats:
            fields.extend(c.fields.all())

        return fields

    @permalink
    def get_absolute_url(self):
        return ('view_region_by_object_type', (), {
            'category_slug': self.slug,
            })


def product_upload_to(instance, filename):
    return os.path.join('users', str(instance.user.id), 'products', str(instance.id), filename)


class ApprovedManager(hstore.Manager):
    def get_query_set(self):
        return super(ApprovedManager, self).get_query_set().filter(is_approved=True, paid_until__gte=datetime.date.today())


class NotApprovedManager(hstore.Manager):
    def get_query_set(self):
        return super(NotApprovedManager, self).get_query_set().filter(is_approved=False)

class NotProlongedManager(hstore.Manager):
    def get_query_set(self):
        return super(NotProlongedManager, self).get_query_set().filter(is_approved=True, paid_until__lt=datetime.date.today())


class NotPaidManager(hstore.Manager):
    def get_query_set(self):
        return super(NotPaidManager, self).get_query_set().filter(paid_until__lt=datetime.date.today()).exclude(deal_type__slug='demand')

class Product(TimeStampedModel):
    user = models.ForeignKey(User)
    deal_type = models.ForeignKey(DealType, verbose_name=u'Вид сделки')
    category = models.ForeignKey(Category, verbose_name=u'Категория', related_name='products')
    slug = models.CharField(max_length=255, blank=True, null=True)

    title = models.CharField(u'Наименование', max_length=255)
    description = models.TextField(u'Описание', blank=True, max_length=1024)
    data = hstore.DictionaryField(db_index=True)
    site = models.ForeignKey(Site)

    is_approved = models.BooleanField(u'Проверено', default=False)
    paid_until = models.DateField(u'Оплачено до', blank=True, default=datetime.date.today())

    objects = hstore.Manager()
    approved_objects = ApprovedManager()
    not_approved_objects = NotApprovedManager()
    not_paid_objects = NotPaidManager()
    not_prolonged_objects = NotProlongedManager()

    class Meta:
        verbose_name = u'Объект'
        verbose_name_plural = u'Объекты'

    def __unicode__(self):
        return self.title

    @permalink
    def get_absolute_url(self):
        return ('view_product', (), {'city': self.locations.all()[0].region.subdomain,
                                     'slug': self.slug,
                                     'product_id': self.id})

    def get_main_image(self):
        try:
            return self.images.all()[0]
        except:
            return None

    def get_price(self):
        try:
            return self.prices.all()[0].price_str()
        except:
            return None

    def get_latest_price(self):
        try:
            return self.prices.all()[0]
        except:
            return None

    def get_latest_location(self):
        try:
            return self.locations.all()[0]
        except:
            return None


    def photos_count(self):
        return self.images.count()

    def videos_count(self):
        return 0

    def panoramas_count(self):
        return 0

    def is_unpaid(self):
        return not self.paid_until or self.paid_until < datetime.date.today()

    def days_remains(self):
        return (self.paid_until - datetime.date.today()).days

    def is_demand(self):
        return self.deal_type.slug == 'demand'

def make_slug(sender, instance, signal, *args, **kwargs):
    instance.slug = slugify(instance.title)

pre_save.connect(make_slug, sender=Product)


class Price(TimeStampedModel):
    """
    Цена продукта
    """
    product = models.ForeignKey(Product, related_name='prices')

    price = models.DecimalField(u'Стоимость', max_digits=12, decimal_places=0, blank=True, null=True)

    price_type = models.IntegerField(choices=DEAL_PRICE_TYPE, blank=True, null=True)
    price_period = models.IntegerField(choices=DEAL_PRICE_PERIOD, blank=True, null=True)

    commission = models.DecimalField(max_digits=12, decimal_places=0, blank=True, null=True)

    pledge = models.DecimalField(max_digits=12, decimal_places=0, blank=True, null=True)

    def price_str(self):
        return u"%s руб." % (self.price, )


class Location(TimeStampedModel):
    """
    Расположение продукта
    """
    product = models.ForeignKey(Product, related_name='locations')

    region = models.ForeignKey(GeoLocation)

    city = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)

    lat = models.FloatField(blank=True, null=True)

django/just_a_code/catalog/templates/catalog/delete_product.html
{% extends "accounts/base.html" %}

{% load thumbnail %}
{% load pagination_tags %}

{% block extra_meta %}{{ block.super }}
{% endblock %}

{% block account_content %}
 <form action="." method="POST" class="form-horizontal">{% csrf_token %}
    <h2>"{{ product.title }}"</h2>
    <h3>Вы действительно хотите удалить эту публикацию?</h3>
    <input class="btn btn-danger" type="submit" value="Удалить">
 </form>
{% endblock %}

django/just_a_code/catalog/templates/catalog/edit_demand.html
{% extends "accounts/base.html" %}

{% load thumbnail %}
{% load pagination_tags %}
{% load crispy_forms_tags %}

{% block extra_meta %}{{ block.super }}
{% endblock %}

{% block header %}
    <h1>Редактирование публикации</h1>
{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
    <li>
        <a href="/accounts/">Личный кабинет</a> <span class="divider">/</span>
    </li>
    <li>
        <a href="/catalog/my_items/">Мои публикации</a> <span class="divider">/</span>
    </li>
    <li class="active">{{ product.title }}</li>
</ul>
{% endblock %}

{% block account_content %}
    <form action="." method="POST" class="form-horizontal">{% csrf_token %}
        {% crispy form form.helper %}
        {% include 'common/elements/form_submit.html' with value='Сохранить' %}
    </form>
{% endblock %}

django/just_a_code/catalog/templates/catalog/edit_product.html
{% extends "accounts/base.html" %}

{% load thumbnail %}
{% load pagination_tags %}
{% load crispy_forms_tags %}

{% block extra_meta %}{{ block.super }}
{% endblock %}

{% block account_content %}
    <ul class="nav nav-tabs">
        <li class="active"><a href="#main" >Основная информация и стоимость</a></li>
        <li><a href="{% url edit_product_map product.id %}" >Расположение на карте</a></li>
        <li><a href="{% url edit_product_photos product.id %}">Фотографии</a></li>
    </ul>

    <form action="." method="POST" class="form-horizontal">{% csrf_token %}

        {% crispy price_form price_form.helper %}

        {% crispy object_form object_form.helper %}

        {% include 'common/elements/form_submit.html' with value='Сохранить' %}
    </form>
{% endblock %}

django/just_a_code/catalog/templates/catalog/edit_product_map.html
{% extends "accounts/base.html" %}

{% load thumbnail %}
{% load pagination_tags %}
{% load crispy_forms_tags %}

{% block extra_meta %}{{ block.super }}
    {% include 'catalog/add_object_wizard/location_script.html' with prefix='' edit_mode=1 %}
{% endblock %}

{% block account_content %}
    <ul class="nav nav-tabs">
        <li><a href="{% url edit_product product.id %}">Основная информация и стоимость</a></li>
        <li class="active"><a href="{% url edit_product_map product.id %}">Расположение на карте</a></li>
        <li><a href="{% url edit_product_photos product.id %}">Фотографии</a></li>
    </ul>

    <form action="." method="POST" class="form-horizontal">{% csrf_token %}

        {% crispy form form.helper %}

        {% include 'common/elements/form_submit.html' with value='Сохранить' %}
    </form>
{% endblock %}

django/just_a_code/catalog/templates/catalog/edit_product_photos.html
{% extends "accounts/base.html" %}

{% load thumbnail %}
{% load pagination_tags %}
{% load crispy_forms_tags %}

{% block extra_meta %}
    {{ block.super }}
{% endblock %}

{% block account_content %}
    <ul class="nav nav-tabs">
        <li><a href="{% url edit_product product.id %}">Основная информация и стоимость</a></li>
        <li><a href="{% url edit_product_map product.id %}">Расположение на карте</a></li>
        <li class="active"><a href="{% url edit_product_photos product.id %}">Фотографии</a></li>
    </ul>

    <ul class="thumbnails">
        {% for i in product.images.all %}
        <li class="span3">
            <div class="thumbnail" style="text-align: center">
                <a href="{{ i.image.url }}">
                    <img src={% thumbnail i.image 200x150 crop %}>
                </a>
                <div class="caption" style="text-align: center">
                    <p><a class="btn btn-mini btn-primary" href="#">Сделать основным</a> <a class="btn btn-mini btn-warning" href="#">Удалить</a></p>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>


    <a href="#" class="btn btn-success">Добавить изображение</a>


{% endblock %}

django/just_a_code/catalog/templates/catalog/my_products.html
{% extends "accounts/base.html" %}

{% load thumbnail %}
{% load pagination_tags %}

{% block extra_meta %}{{ block.super }}
{% endblock %}

{% block account_content %}
    {% autopaginate products 10 %}

    <p class="pull-right">
        <a href="{% url add_object %}" class="btn" style="margin-right: 5px">Добавить публикацию</a>
    </p>

    <div class="clearfix"></div>

    <br/>


    <table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>
            Фото
        </th>
        <th>
            Информация
        </th>
        <th style="text-align: center">
            Действия
        </th>
    </tr>
    </thead>
    {% for i in products %}
        <tr>
            <td style="width: 130px">
                {% if i.get_main_image %}
                    <img src="{% thumbnail i.get_main_image.image 130x100 crop %}"/>
                {% else %}
                    {% if i.deal_type.slug == 'demand' %}
                    <div style="width: 130px; height: 65px; background-color: #c0c0c0; padding-top: 35px; text-align: center">
                        <i>Спрос</i>
                    </div>

                    {% else %}
                    <div style="width: 130px; height: 75px; background-color: #c0c0c0; padding-top: 25px; text-align: center">
                        <i>Нет<br/> изображения</i>
                    </div>
                    {% endif %}
                {% endif %}
            </td>
            <td>
                <h5 style="margin-top: 0; font-size: 15px"><a href="{{ i.get_absolute_url }}">{{ i.title|truncatechars:50 }}</a></h5>

                {% if i.deal_type.slug == 'demand' %}
                    <p>
                    {{ i.description|truncatechars:50 }}
                        </p>
                {% else %}
                <h4 style="margin: 15px 0px">{{ i.get_price }}</h4>
                {% endif %}

                {% if i.is_approved %}
                    <span class="label label-success">Проверено</span>
                {% else %}
                    <span class="label label-warning">На модерации</span>
                {% endif %}

                |

                {% if i.is_unpaid %}
                    {% if i.is_demand %}
                        <span class="label label-important">Не продлено</span>
                    {% else %}
                        <span class="label label-important">Не оплачено</span>
                    {% endif %}
                {% else %}
                    {% if i.is_demand %}
                        <span class="label" style="color: #000000">Показывать до: {{ i.paid_until|date:"d.m.Y" }}. Осталось дней: {{ i.days_remains }}</span>
                    {% else %}
                        <span class="label" style="color: #000000">Оплачено до: {{ i.paid_until|date:"d.m.Y" }}. Осталось дней: {{ i.days_remains }}</span>
                    {% endif %}
                {% endif %}


                <br/>
                <span class="muted" style="font-size: 11px">{{ i.get_latest_location.region }} - {{ i.deal_type }} / {{ i.category }} - {{ i.created|date:"d.m.Y" }}</span>
            </td>
            <td style="text-align: center; width: 100px; padding-left: 15px; padding-top: 18px">
                {% if i.deal_type.slug == 'demand' %}
                <a href="{% url edit_demand i.id %}" style="width: 80px; display: block; margin-bottom: 5px" class="btn btn-mini btn-success">Редактировать</a>
                {% else %}
                <a href="{% url edit_product i.id %}" style="width: 80px; display: block; margin-bottom: 5px" class="btn btn-mini btn-success">Редактировать</a>
                {% endif %}
                {% if i.is_demand %}
                    <a href="{% url payments_pay_product i.id %}" style="width: 80px; display: block; margin-bottom: 5px" class="btn btn-mini btn-info">Продлить</a>
                {% else %}
                    <a href="{% url payments_pay_product i.id %}" style="width: 80px; display: block; margin-bottom: 5px" class="btn btn-mini btn-info">Оплатить</a>
                {% endif %}
                <a href="{% url delete_product i.id %}" style="width: 80px; display: block; margin-bottom: 5px" class="btn btn-mini btn-warning">Удалить</a>
            </td>
        </tr>
    {% empty %}
        <tr>
        <td colspan="3" style="text-align: center">
            <h5>Нет публикаций</h5>
        </td>
        </tr>
    {% endfor %}


    </table>

    {% paginate %}
{% endblock %}

django/just_a_code/catalog/templates/catalog/successfully_added.html
{% extends "base.html" %}

{% block extra_meta %}
    {{ block.super }}
    <script type="text/javascript" charset="utf-8">

    </script>
{% endblock %}


 {% block header %}
    <h1>Публикация успешно добавлена</h1>
{% endblock %}

{% block content %}
    {% if not product.is_demand %}
        <p>Стоимость показа публикации на Salea <strong>{{ sc.price_per_day }} рублей в сутки</strong>.</p>
    {% endif %}

    <p>После проверки объявления модератором вы получите письмо с подтверждением показа.</p>

    {% if not product.is_demand %}
        <p>Для того чтобы оплатить показ этой публикации, воспользуейтесь формой ниже или кликните по кнопке "Оплатить".</p>
    {% else %}
        <p>Выберите срок показа публикации на форме ниже. Размещение в категории "Спрос" бесплатно.</p>
    {% endif %}

    <hr/>
    <h5>Заголовок публикации: </h5>
    <h3>{{ product.title }} [ID: {{ product.id }}]</h3>

    <form action="." class="form" method="POST">{% csrf_token %}
        {% include 'common/elements/form.html' %}
        {% if not product.is_demand %}
            {% include 'common/elements/form_submit.html' with text='Перейти к оплате' %}
        {% else %}
            {% include 'common/elements/form_submit.html' with text='Опубликовать' %}
        {% endif %}
    </form>
{% endblock %}

django/just_a_code/catalog/templates/catalog/view_region.html
{% extends "base.html" %}

{% load thumbnail %}
{% load pagination_tags %}
{% load catalog_tags %}

{% block title %}Каталог - {{block.super}}{% endblock %}

{% block extra_meta %}{{ block.super }}
{% endblock %}

{% block header %}{% endblock %}

{% block content %}
    <div class="row">
        <div class="span12">
            <h1>
                КАТАЛОГ
                {% if category %}<small>{{ category|lower }}</small>{% endif %}
                {% if deal_type %}<small>{{ deal_type|lower }}</small>{% endif %}
            </h1>
        </div>
    </div>


    {% if products %}
        {% if deal_type.slug != 'demand' %}
        <div class="row">
            <div class="span12">

                <form class="form form-inline well well-small" style="height: 50px">
                    <div class="span6" style="margin-top: 10px">
                        <label>Цена от: </label>
                        <input class="input-small" size="12" type="text" name="price_from" id="DoubleTrack-5-InputMin" value="{{ price_from|default:'' }}" />
                        <label>до, </label>
                        <input class="input-small" size="12" type="text" name="price_to" id="DoubleTrack-5-InputMax" value="{{ price_to|default:'' }}" />
                        <label>руб.</label>
                        <input type="submit" class="btn">
                    </div>

                    <div class="span4">
                        <div id="DoubleTrack-5" class="DoubleTrackBar" style="visibility: hidden;">
                            <div id="DoubleTrack-5-Tracker" class="Tracker">
                                <img src="/static/img/gui.png" alt='' class="fll" />
                                <img src="/static/img/gui.png" alt='' class="flr" />
                                <span class="fll text" id="DoubleTrack-5-LeftText"></span>
                                <span class="flr text" id="DoubleTrack-5-RightText"></span>
                            </div>
                        </div>
                    </div>
                </form>

                <div class="clear"></div>
                <script type="text/javascript" defer="defer">
                    $(document).ready(function(){

                    function classFilter(r,m,not){
                        m = " " + m + " ";
                        var tmp = [];
                        for ( var i = 0; r[i]; i++ ) {
                            var pass = (" " + r[i].className + " ").indexOf( m ) >= 0;
                            if ( not ^ pass )
                                tmp.push( r[i] );
                        }
                        return tmp;
                    }

                    var DoubleTrackBar = new cDoubleTrackBar('DoubleTrack-5', 'DoubleTrack-5-Tracker', {
                        OnUpdate: function(){
                            $('#DoubleTrack-5-LeftText').html(this.leadSpaces(this.MinPos)+" руб.");
                            $('#DoubleTrack-5-RightText').html(this.leadSpaces(this.MaxPos)+" руб.");
                            $('#DoubleTrack-5-InputMin').val(this.MinPos);
                            $('#DoubleTrack-5-InputMax').val(this.MaxPos);

                            this.Tracker.style.backgroundPosition = -this.TrackerLeft + 'px center';
                            if (this.fix)
                                for (var i in this.fix)
                                    this.fix[i].style.left = (this.TrackerRight - this.TrackerLeft) + 'px';

                            var distance = Math.ceil(($('#DoubleTrack-5-RightText').offset().left - parseInt($('#DoubleTrack-5-RightText').css('margin-left')) + parseInt($('#DoubleTrack-5-LeftText').css('margin-left')) - $('#DoubleTrack-5-LeftText').offset().left - $('#DoubleTrack-5-LeftText').width() - 40)/2);
                            if(distance <= 0)
                            {
                                var left_margin = (distance);
                                var right_margin = (-distance) - 50;
                                console.log($('#DoubleTrack-5-RightText').offset().left + ' - ' + $('#DoubleTrack-5-LeftText').offset().left + ' - ' + $('#DoubleTrack-5-LeftText').width());
                                console.log(distance);
                                $('#DoubleTrack-5-LeftText').css('margin-left', left_margin + 'px');
                                $('#DoubleTrack-5-RightText').css('margin-left', right_margin + 'px');
                            }
                            else
                            {
                                $('#DoubleTrack-5-LeftText').css('margin-left', 0);
                                $('#DoubleTrack-5-RightText').css('margin-left', '-50px');
                            }
                        },
                        Min: {{ min_max_price.min }},
                        Max: {{ min_max_price.max }},
                        FingerOffset: 0,
                        MinSpace: 14400,
                        RoundTo: 100,
                        Margins: 0,
                        FormatNumbers: true,
                        AllowedValues: true
                    });
                    DoubleTrackBar.AutoHairline(4);
                    DoubleTrackBar.fix = classFilter(DoubleTrackBar.Tracker.getElementsByTagName('*'), 'flr');
                    DoubleTrackBar.Track.style.visibility = 'visible';
                        {% if price_from and price_to %}
                    DoubleTrackBar.SetLeftValue({{ price_from }});
                    DoubleTrackBar.SetRightValue({{ price_to }});
                            {% endif %}


                        $('#DoubleTrack-5-InputMin').blur(function()
                        {
                            if($(this).val() == parseInt($(this).val()))
                            {
                                DoubleTrackBar.SetLeftValue(parseInt($(this).val()));
                            }
                        })

                        $('#DoubleTrack-5-InputMax').blur(function()
                        {
                            if($(this).val() == parseInt($(this).val()))
                            {
                                DoubleTrackBar.SetRightValue(parseInt($(this).val()));
                            }
                        })


                    })
                </script>
            </div>
        </div>
        {% endif %}
    {% endif %}

    <div class="row">
        <div class="span9">
            {% for p in products %}
                {% if p.deal_type.slug != 'demand' %}
                    {% include 'catalog/elements/item.html' %}
                {% else %}
                    {% include 'catalog/elements/item_demand.html' %}
                {% endif %}
            {% empty %}
                <h3>Нет публикаций подходящих под выбранные критерии</h3>
            {% endfor %}

        </div>
        <div class="span3">
            <ul class="nav nav-list">
                <li class="nav-header">По типу сделки</li>
                {% for dt in deal_types %}
                    <li {% if deal_type == dt %}class="active"{% endif %}><a href="{% url view_region_by_deal_type city dt.slug %}">{{ dt }}</a> </li>
                {% endfor %}


                <li class="nav-header">Предложения по разделам</li>
                {% for c in deal_type.category_set.all %}
                    <li {% if category == c %}class="active" {% endif %}><a href="{% url view_region_by_object_type_and_deal_type city deal_type.slug c.slug %}">{{ c }}</a> </li>
                {% endfor %}

            </ul>
        </div>

    </div>



{% endblock %}